### ISSUE TITLE
Missing character '...'

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/BMFont#13]
問題：
翻訳文中に存在する3点リーダ「…」（2バイト文字1文字）がゲーム中では表示されない。

再現性：
常に

再現手順：
1. プレイを開始し、1450年ごろまで進める。
2. ルネサンス発祥のダイアログが表示される。
3. 翻訳文では「これはすべてを変えるな…」のはずが、ダイアログでは末尾の「…」が表示されない。

原因：
フォントに3点リーダが含まれていないことが原因だと思われる。

解決策：
最新版のBMFontには3点リーダに相当する文字コードが割り振られているので、
フォントを再生成すれば解決する可能性がある。

**Comment by matanki-saito** [comment]
更に追加で問題があり、三点リーダー（u2026）はCP1252ではu85にマッピングされており（下記参照）、BMFontでは三点リーダーはu2026ではなくて、u85としてマッピングするように改造していました。
![image](https://user-images.githubusercontent.com/35730970/49962425-906bf800-ff58-11e8-93c3-209fb9342215.png)
そのため、生成用文字セットに三点リーダーを含めたとしても、正常に出ませんでした。

**Comment by matanki-saito** [comment]
修正BMFontを使い、EU4fontcreateのスクリプトを回せば下記のように三点リーダーが表示されるようになります。
![image](https://user-images.githubusercontent.com/35730970/49962865-c65dac00-ff59-11e8-9c1e-a577f493dc7d.png)

**Comment by matanki-saito** [comment]
修正したフォントです
[fonts_eu4.zip](https://github.com/matanki-saito/BMFont/files/2677422/fonts_eu4.zip)
